# Generated by Django 5.2.6 on 2025-10-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lising', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='equipment',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['-time_create'], name='lising_equi_time_cr_cea693_idx'),
        ),
    ]
