# Generated by Django 5.2.6 on 2025-10-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lising', '0002_alter_equipment_options_equipment_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
