# Generated by Django 5.2.6 on 2025-10-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lising', '0003_alter_equipment_slug'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='equipment',
            name='lising_equi_time_cr_cea693_idx',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0),
        ),
    ]
